=== WangZhenfei/clingen-data-model/source/main/resources/gene.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://clingen.org/dm/allele/v1"
	targetNamespace="http://clingen.org/dm/allele/v1" xmlns:f="http://hl7.org/fhir"
	elementFormDefault="qualified" version="0.0.82">

	<xs:import namespace="http://hl7.org/fhir" schemaLocation="fhir-base.xsd" />

	<xs:element name="Gene" type="Gene">
		<xs:annotation>
			<xs:documentation>The concept of a specific Gene. Should be identified with an HGNC identifier.</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:complexType name="Gene">
		<xs:complexContent>
			<xs:extension base="f:Resource">
				<xs:sequence>
					<xs:element name="identifier" type="f:Identifier"
						maxOccurs="unbounded" />
					<xs:element name="symbol" type="f:string" minOccurs="0" />
					<xs:element name="name" type="f:string" minOccurs="0" />
					<xs:element name="alias" type="f:string" nillable="true"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="relatedReferenceSequence" type="Gene.RelatedReferenceSequence"
						nillable="true" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Gene.RelatedReferenceSequence">
		<xs:complexContent>
			<xs:extension base="f:BackboneElement">
				<xs:sequence>
					<xs:element name="type" type="GeneRelatedRefSeqType"
						minOccurs="0" />
					<xs:element name="target" type="f:ResourceReference" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="GeneRelatedRefSeqType-list">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gene" />
			<xs:enumeration value="transcript" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="GeneRelatedRefSeqType">
		<xs:complexContent>
			<xs:extension base="f:Element">
				<xs:sequence />
				<xs:attribute name="value" type="GeneRelatedRefSeqType-list" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>





</xs:schema>

=== WangZhenfei/clingen-data-model/source/main/resources/example-xml/G102-BRCA1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Gene xmlns="http://clingen.org/dm/allele/v1" xmlns:f="http://hl7.org/fhir"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://clingen.org/dm/allele/v1 ../clingen-xsd/gene.xsd "
	id="G102">
	<identifier>
		<f:use value="official"></f:use>
		<f:label value="BRCA1"></f:label>
		<f:system value="http://www.genenames.org/"></f:system>
		<f:value value="HGNC:1100"></f:value>
	</identifier>
	<identifier>
		<f:system value="http://www.ncbi.nlm.nih.gov/gene"></f:system>
		<f:value value="672"></f:value>
	</identifier>
	<symbol value="BRCA1"></symbol>
	<name value="breast cancer 1, early onset"></name>
	<alias value="IRIS"></alias>
	<alias value="PSCP"></alias>
	<alias value="BRCAI"></alias>
	<alias value="BRCC1"></alias>
	<alias value="FANCS"></alias>
	<alias value="PNCA4"></alias>
	<alias value="RNF53"></alias>
	<alias value="BROVCA1"></alias>
	<alias value="PPP1R53"></alias>
</Gene>
